spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate # trust Flyway to create schema; fail if mismatch
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace # shows SQL bind parameters (helpful in dev)
